# ============================================================
# 資料庫設定 — 記憶體資料庫 H2
# ============================================================
spring.datasource.url=jdbc:h2:mem:finance_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA 設定
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# 自動初始化 Database
spring.sql.init.mode=always
spring.sql.init.schema-locations=file:../DB/schema.sql
spring.sql.init.data-locations=file:../DB/data.sql
spring.sql.init.encoding=UTF-8

# Server
server.port=8080

# 上傳大小限制
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
